### ISSUE TITLE
Unable to pull groovy official images

### ISSUE THREAD

**Issue by 452** [groovy/docker-groovy#1]
repository on docker hub unavailable

**Comment by Starefossen** [comment]
It is still pending official status ref. docker-library/official-images#2575

**Comment by keeganwitt** [comment]
Sorry for the confusion.  I updated the readme in preparation for their being published.  Stay tuned.  I'll make sure to let everyone know as soon as it's published at [users@groovy.apache.org](http://groovy-lang.org/mailing-lists.html).

**Comment by Starefossen** [comment]
It's alive 🎉 https://hub.docker.com/_/groovy/
