### ISSUE TITLE
Add Support for ARM64V8 architecture 

### ISSUE THREAD

**Issue by odidev** [groovy/docker-groovy#33]
Hi,

The Groovy docker package is building and running fine at my end for ARM64v8 architecture.
```
Branch used to build is: jre8
```
Please suggest, what needs to be done to raise the request to add support for ARM64v8 arch at official docker library too.

Regards,

**Comment by keeganwitt** [comment]
You need to make this request against the upstream [openjdk](https://github.com/docker-library/openjdk) image.  Once they include it, I can include in here.

**Comment by odidev** [comment]
@keeganwitt : [openjdk](https://hub.docker.com/_/openjdk/), already mentions the support for ```arm64v8``` architecture.
I am skeptical, whether I really need to raise request to include ```arm64v8``` support there.

Can you be a bit more clear, what needs to be done at my end?

**Comment by lag-linaro** [comment]
`docker pull groovy` now works on my ARM64 platform.

Thanks for your support on this.  Looks like this ticket can now be closed.
