### ISSUE TITLE
Can't pull groovy:latest

### ISSUE THREAD

**Issue by andrewsomesyoung** [groovy/docker-groovy#41]
Whenever we try to pull the latest groovy docker image we get the following error:

docker: no matching manifest for unknown in the manifest list entries.

This is true on Mac and CentOS 7 build machines.

**Comment by SiarheiPaulovich** [comment]
docker pull groovy:jdk8
jdk8: Pulling from library/groovy
no matching manifest for unknown in the manifest list entries
(same for linux and mac)

checked jdk7/jdk9 - ok

**Comment by keeganwitt** [comment]
I've raised this issue with the Docker Library folks: https://github.com/docker-library/official-images/issues/5082.

**Comment by mamsterla** [comment]
What is the workaround for MacOS - Groovy 2.5.4 - jre8/jdk8?

**Comment by keeganwitt** [comment]
I've got a PR open to help with build stability.  Hopefully we'll get the image pushed soon: https://github.com/docker-library/official-images/pull/5165

**Comment by keeganwitt** [comment]
Build is [complete](https://travis-ci.org/docker-library/official-images/builds/466814944) and I'm able to pull now.
