### ISSUE TITLE
Groovy Docker container doesnt start

### ISSUE THREAD

**Issue by Jagdish0886** [groovy/docker-groovy#50]
I have used the code in Dockerfile and using docker-compose.yml i have build the image successfully.
Though the image is built successfully, i am not able to start the container, it exits abruptly.

When i see the docker logs it shows for the groovy container, which i believe it created successfully:
----------------------
[jenkins@localhost jenkins_data]$ docker logs c489d6d45f4d
Aug 27, 2019 10:45:26 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Groovy Shell (3.0.0-beta-3, JVM: 12.0.2)
Type ':help' or ':h' for help.
-----------------

[jenkins@localhost jenkins_data]$ docker-compose logs -f groovy
Attaching to groovy_server
groovy_server  | Aug 27, 2019 10:45:26 AM java.util.prefs.FileSystemPreferences$1 run
groovy_server  | INFO: Created user preferences directory.
groovy_server  | Groovy Shell (3.0.0-beta-3, JVM: 12.0.2)
groovy_server  | Type ':help' or ':h' for help.
groovy_server  | -------------------------------------------------------------------------------
groovy_server  | groovy:000> groovy_server exited with code 0
[jenkins@localhost jenkins_data]$

-------------------------
everytime i start the container, I see it in an exited status:

CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                                   NAMES
c489d6d45f4d        groovy                    "groovysh"               17 minutes ago      Exited (0) 1 second ago                                           groovy_server

Please suggest, how can i start my groovy container.

**Comment by keeganwitt** [comment]
By default, the image runs the command `groovysh`.  This is an interactive shell (repl), which probably doesn't make sense to use in a Docker Compose context.  What are you trying to do in your case?

**Comment by keeganwitt** [comment]
Closing stale issue.  Reply with further information if you believe there's an issue.
